### ISSUE TITLE
App Catalog Breadcrumb always shows EFK-STACK-APP for all apps

### ISSUE THREAD

**Issue by albuch** [giantswarm/happa#2199]
# Actual behaviour

1. Click on any App in App Calatog selection
2. Verify that Breadcrumb is HOME>APPS>EFK-STACK-APP for any app

# Expected behaviour 
Breadcrum is  HOME>APPS>[App Name]

Happa v1.4.2

**Comment by oponder** [comment]
Thanks for reporting this!  We'll get a fix out soon
