### ISSUE TITLE
Release Notes URL in footer wrong

### ISSUE THREAD

**Issue by albuch** [giantswarm/happa#2433]
For Happa v1.8.0 the link URL in the Footer to the release notes is missing the `v` in the version part.
URL that is currently there: https://docs.giantswarm.io/changes/web-ui/happa/1.8.0/ which leads to a 404.
URL that should be there: https://docs.giantswarm.io/changes/web-ui/happa/v1.8.0/

**Comment by axbarsan** [comment]
Hi @albuch, thank you for finding this. We'll fix it right away ✅

**Comment by axbarsan** [comment]
This is now fixed in version `v1.8.1`
