### ISSUE TITLE
Use info endpoint to determine allowed instance types

### ISSUE THREAD

**Issue by oponder** [giantswarm/happa#265]
Now that we have the info endpoint, lets use it to show the user the right list of instance types during cluster creation.

Note: Happa needs a bit more info about an instance type to show users things like a description and what capabilities it has.

The info endpoint doesn't expose this extra information about an instance type. So Happa will still need to have some changes done to it whenever a new instance type is added to the allowed list.

**Comment by marians** [comment]
@oponder Can you tell me where the list of allowed instance types / VM sizes is now taken from? I have a hard time finding it in happa.

**Comment by oponder** [comment]
It's in the info endpoint, source of truth is the installations repo.

But it's served from `cluster-service`, up through the `api` 

It's the `workers.instance_type.options` key from the info endpoint:

https://docs.giantswarm.io/api/#tag/info

**Comment by marians** [comment]
So this means we can close this old issue :)
