### ISSUE TITLE
Cluster table columns too small/overlapp on organization view

### ISSUE THREAD

**Issue by albuch** [giantswarm/happa#2887]
1. Navigate to `http://localhost/organizations/org_name`
2. Verify that first two colums `Cluster ID`and `Name` of Cluster table overlapp

Tested with Firefox 93.0 (64-Bit) on MacOS 11.6.1 and Win10
Works with latest Safari.

**Comment by axbarsan** [comment]
Can you please post a screenshot?

**Comment by albuch** [comment]
![Screenshot 2021-11-03 at 13-02-24 Organization Details division-alpha Giant Swarm](https://user-images.githubusercontent.com/9433608/140059440-b33986a0-8f57-4b40-9e9d-2682b23f7004.png)

**Comment by axbarsan** [comment]
Thank you, I'll take a look

**Comment by axbarsan** [comment]
The fix will be available in the next version. Thank you for reporting the bug 👍
