### ISSUE TITLE
Tests to add to Happa

### ISSUE THREAD

**Issue by oponder** [giantswarm/happa#759]
### Authentication
- [x] Login with password
- [x] Login with auth0
- [x] Logout
- [x] Password reset
- [x] Signup
- [x] Changing password
- [x] Changing email

### Cluster Management
- [x] Creating a cluster 
- [x] Deleting a cluster
- [x] Changing scaling settings of a cluster
- [x] Creating a keypair
- [x] Creates a v5 cluster and redirect to details view
- [x] Switch to v4 form, creates a v4 cluster and redirect to details view
- [x] The user is redirected to list when cluster doesn't exist
- [x] Cluster list shows all clusters, each one with its details and resources, for the selected organization. 

### V4 Cluster Management (AWS, KVM, Azure)
- [x] it deletes a cluster
- [x] it patches name
- [x] AWS, it renders cluster data
- [x] AWS, it scales with the scaling modal correctly
- [x] Azure render cluster data 
- [x] Azure scaling
- [x] KVM render cluster data
- [x] KVM scaling
- [x] Key pairs tab: renders data correctly
- [x] Apps tab: renders data correctly

###  V5 Cluster management
- [x] It renders cluster data without nodes ready
- [x] with nodes ready
- [x] It renders all node pools in store
- [x] It shows the menu when button is clicked
- [x] It scales a node pool correctly
- [x] It patches a np name
- [x] It sorts node pools
- [x] It deletes a V5 cluster
- [x] It deletes a node pool
- [x] It adds node pool
- [x] Key pairs tab: renders data correctly
- [x] Apps tab: renders data correctly

### Org management
- [x] Creating an org
- [x] Deleting an org
- [x] Adding a member to an org
- [x] Removing a member from an org
- [x] Viewing list of all orgs

### User management
- [x] Renders users correctly
- [x] Invites new users
- [x] Deletes existing users
- [x] Removes the expiration date from user invitations

### App catalog
- [x] App catalog viewing
- [x] App installation
- [x] Editing App

### UI Components
- [x] V4 Scale cluster modal

### Getting Started Guide
- [x] Navigating through pages
- [x] Get started button behaviour on dashboard and cluster detail page

**Comment by ograu** [comment]
On SIG Front End meeting (5 Dec) we agreed on have all boxes checked before 3 months from now. This is 5 Mar 2020

**Comment by oponder** [comment]
Closing this issue! Great work everyone! 81% test coverage right now, that's pretty great.
