### ISSUE TITLE
Sign in advanceForm bug when using password manager

### ISSUE THREAD

**Issue by wind0r** [giantswarm/happa#812]
When using a password manger and validating the password the second time the next button gets stuck in disabled state and does not start showing the terms of service and agree button. After leaving and entering the second password field again the next button gets enabled and it is possible to progress. See gif :) 
![signinbugpwmanager](https://user-images.githubusercontent.com/2079851/67972359-ce284c80-fc0e-11e9-853a-bf6de178eca5.gif)

I just had the small look at the code and I think doing this step dialog via CSS is quite fancy. I am wondering why this approach was chosen since I would have used react conditional renders instead of it.

**Comment by axbarsan** [comment]
This was fixed some time ago during a refactor of the page. 👍
